### ISSUE TITLE
vim-emu incompatible with OSM Release 9

### ISSUE THREAD

**Issue by declspec** [containernet/vim-emu#4]
I was just trying to use vim-emu in the latest OSM release (Release NINE). When deploying a Network Service the emulator was returning a 500, checking the logs I found that it seemed to be caused by an invalid keyword argument being passed to the HostConfig constructor:

```
ERROR:api.openstack.nova:emuvim.api.openstack.openstack_dummies.nova_dummy_api: Could not create the server.
Traceback (most recent call last):
  File "/vim-emu/src/emuvim/api/openstack/openstack_dummies/nova_dummy_api.py", line 257, in post
    self.api.compute._start_compute(server)
  File "/vim-emu/src/emuvim/api/openstack/compute.py", line 481, in _start_compute
    properties=server.properties)
  File "/vim-emu/src/emuvim/dcemulator/node.py", line 275, in startCompute
    **params
  File "/vim-emu/src/emuvim/dcemulator/net.py", line 272, in addDocker
    self, label, cls=EmulatorCompute, **params)
  File "/containernet/mininet/net.py", line 1058, in addDocker
    return self.addHost( name, cls=cls, **params)
  File "/containernet/mininet/net.py", line 242, in addHost
    h = cls( name, **defaults )
  File "/vim-emu/src/emuvim/dcemulator/node.py", line 57, in __init__
    Docker.__init__(self, name, dimage, **kwargs)
  File "/containernet/mininet/node.py", line 825, in __init__
    storage_opt=self.storage_opt
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 587, in create_host_config
    return HostConfig(*args, **kwargs)
```

I had a quick look at the [changelogs](https://docker-py.readthedocs.io/en/stable/change-log.html#id103) for the Docker pip package and noticed that the `storage_opt` kwarg is only supported from version >= 2.1.0.

I manually installed version 2.1.0 in the container:
```
pip install docker==2.1.0
```
and this resolved the issue. Is there any reason to not bump the Docker python package version to at least 2.1.0? The base containernet image installs the latest version of Docker (4.x.x).

There is a commit (https://github.com/containernet/vim-emu/commit/619e6b39eb58b77f4ff501f7879e9cfe2ff49701) mentioning that vim-emu requires 2.0.2 but doesn't go into detail as to why.

**Comment by mpeuster** [comment]
I updated the install script in this repo to use 4.4.1.
